USE [master]
GO

/****** Object:  Database [LoanAppdb]    Script Date: 28-03-2024 15:47:31 ******/
CREATE DATABASE [LoanAppdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LoanAppdb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS01\MSSQL\DATA\LoanAppdb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LoanAppdb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS01\MSSQL\DATA\LoanAppdb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LoanAppdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LoanAppdb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LoanAppdb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LoanAppdb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LoanAppdb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LoanAppdb] SET ARITHABORT OFF 
GO

ALTER DATABASE [LoanAppdb] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [LoanAppdb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LoanAppdb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LoanAppdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LoanAppdb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LoanAppdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LoanAppdb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LoanAppdb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LoanAppdb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LoanAppdb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [LoanAppdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LoanAppdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LoanAppdb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LoanAppdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LoanAppdb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LoanAppdb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [LoanAppdb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LoanAppdb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LoanAppdb] SET  MULTI_USER 
GO

ALTER DATABASE [LoanAppdb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LoanAppdb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LoanAppdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LoanAppdb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LoanAppdb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LoanAppdb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [LoanAppdb] SET QUERY_STORE = ON
GO

ALTER DATABASE [LoanAppdb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [LoanAppdb] SET  READ_WRITE 
GO

